FROM node:20-bookworm-slim

WORKDIR /app

# Install dependencies for better-sqlite3
RUN apt-get update && apt-get install -y --no-install-recommends clang libc++-dev libc++abi-dev && rm -rf /var/lib/apt/lists/*

# Copy dependency definitions first to leverage Docker cache
COPY package.json yarn.lock ./
COPY packages/ ./packages/
COPY worker/package.json ./worker/package.json


# Install all dependencies
RUN yarn install --frozen-lockfile

# Copy the rest of the worker source code
COPY worker/ ./worker/

# Start the worker in production mode
CMD ["yarn", "--cwd", "worker", "start"]
